### ISSUE TITLE
Jetson Nano

### ISSUE THREAD

**Issue by wgthompson** [RidgeRun/NVIDIA-Jetson-IMX477-RPIV3#1]
Hello,
Thank you for this driver we have all been so anxiously waiting for.

Is this compatible with the jetson nano, and if yes, would implementation be any different?
Thanks,
Will

**Comment by rrcarlosrodriguez** [comment]
Hi @wgthompson , current patch works for Xavier NX. For Jetson Nano the driver should be compatible but the DTB might need some changes, but we haven't tested yet. We'll do next week and will release a new patch for Nano if needed. I will let you know once it is tested and available

**Comment by wgthompson** [comment]
Cool, will leave open till then thanks

**Comment by rrcarlosrodriguez** [comment]
Hi @wgthompson , we just updated the repository including Jetson Nano support. Please check and let us know if if works for you
