### ISSUE TITLE
Jetson Nano Error at Compile kernel, device tree and modules:

### ISSUE THREAD

**Issue by nr-patel** [RidgeRun/NVIDIA-Jetson-IMX477-RPIV3#10]
I am getting following error after running:
make -C kernel/kernel-4.9/ ARCH=arm64 O=$KERNEL_OUT CROSS_COMPILE=${CROSS_COMPILE} -j4 Image
Error:arch/arm64/Makefile:49: LSE atomics not supported by binutils

**Comment by rrcarlosrodriguez** [comment]
Hi @nr-patel , just a quick question, are you running the compilation procedure in your host machine or inside the Jetson Nano?

**Comment by nr-patel** [comment]
Hello @rrcarlosrodriguez ,

I have already setup my Jetson Nano, so running compilation procedure from Jetson Nano. I am just following steps from option B to add driver patch. When will be option A steps will be available for Jetson Nano.

Thanks,
Nikhil

**Comment by rrcarlosrodriguez** [comment]
Compilation procedure should be done inside you host PC, not inside the Jetson Nano.

Option A will be available next week. We already received the Jetson Nano B01 version and will be working on it this week
