### ISSUE TITLE
Jeston NX 4.9 kernel

### ISSUE THREAD

**Issue by nandra** [RidgeRun/NVIDIA-Jetson-IMX477-RPIV3#11]
I'm using meta-tegra with yocto and would like to give a try this driver. I'm using dunfell release which contains: linux-tegra-4.9.140 kernel revision. Does this driver work also with this updated kernel (original documentation tells about 4.4. kernel). Thanks.

**Comment by rrcarlosrodriguez** [comment]
Hi @nandra. Yes, the driver works for Kernel 4.9. Where did you read the driver works for 4.4? That might be a documentation issue

**Comment by nandra** [comment]
Hi, I've used patch and when apply to 4.9. kernel need to adjust some files because paths was different. But driver compile fine. Thanks.
