### ISSUE TITLE
Driver Installation Killed Bluetooth & WiFi

### ISSUE THREAD

**Issue by eileenjkim** [RidgeRun/NVIDIA-Jetson-IMX477-RPIV3#18]
I installed the driver for my Jetson NX dev kit via kernel installation, and it doesn't appear to be working with my Arducam IMX477. Additionally, after driver installation, it appears my WiFi and Bluetooth drivers aren't working.

**Comment by rrcarlosrodriguez** [comment]
Could you please run the following commands in the board and paste the output here?
 `lsmod` 
`uname -a`

**Comment by eileenjkim** [comment]
Certainly. Attached.
![Screenshot from 2020-10-15 17-39-51](https://user-images.githubusercontent.com/36675897/96276162-7b62b480-0f87-11eb-8b04-8a8974b10069.png)

**Comment by eileenjkim** [comment]
Reflashed, didn't apt upgrade, and worked fine.
