### ISSUE TITLE
Jetpack 4.5 compatibility?

### ISSUE THREAD

**Issue by LFRS** [RidgeRun/NVIDIA-Jetson-IMX477-RPIV3#28]
Hi,

Will this driver be updated to the Jetpack 4.5?
I was hoping it would be built into the jetpack 4.5 natively but it didn't.

Thanks,
Luis

**Comment by rrcarlosrodriguez** [comment]
Hi @LFRS , support for Jetpack 4.5 was already added, you can find it in our master branch.
