### ISSUE TITLE
No IMX477 Support for Jetson Nano a02 in L4T 32.5 Debian Package

### ISSUE THREAD

**Issue by Nitepone** [RidgeRun/NVIDIA-Jetson-IMX477-RPIV3#31]
The supplied `nvidia-l4t-kernel-dtbs_4.9.201-tegra-32.5.0-20210115145440_arm64.deb` for Jetson Nano seems to include the `tegra210-p3448-0000-p3449-0000-a02.dtb` as supplied by Nvidia, not the one built with this patch. It appears that only `tegra210-p3448-0000-p3449-0000-b00.dtb` has been built with the imx477 patch in place.

This is apparent when decompiling the device tree and investigating the build name and times. The a02 release was built with a path that looks like Nvidia's and the build time corresponds to other base Jetpack 4.5 DTBs.

In the b00 device tree (`tegra210-p3448-0000-p3449-0000-b00.dtb`):
```
nvidia,dtbbuildtime = "Feb  3 2021\012:11:47";
nvidia,dtsfilename = "/media/test/home/crodriguez/nvidia/kernels/nano-drivers/kernel/kernel-4.9/arch/arm64/boot/dts/../../../../../../hardware/nvidia/platform/t210/porg/kernel-dts/tegra210-p3448-0000-p3449-0000-b00.dts";
```

In the a02 device tree (`tegra210-p3448-0000-p3449-0000-a02.dtb`):
```
nvidia,dtbbuildtime = "Jan 15 2021\014:47:47";
nvidia,dtsfilename = "/dvs/git/dirty/git-master_linux/kernel/kernel-4.9/arch/arm64/boot/dts/../../../../../../hardware/nvidia/platform/t210/porg/kernel-dts/tegra210-p3448-0000-p3449-0000-a01.dts";
```

Is there supposed to be support for the a02? The wiki seems to provide instructions for it.

**Comment by lucomsky** [comment]
It works for me with JP4.5 on A02, check it!
